FROM nextcloud:14-fpm-alpine

COPY redis.config.php /usr/src/nextcloud/config/redis.config.php
COPY my.config.php /usr/src/nextcloud/config/my.config.php
COPY ./apps_custom /usr/src/nextcloud/apps_custom
