FROM nextcloud:13-fpm-alpine

COPY redis.config.php /usr/src/nextcloud/config/redis.config.php
COPY my.config.php /usr/src/nextcloud/config/my.config.php
COPY ./custom_apps /usr/src/nextcloud/custom_apps
