version: '3.6'

networks:
    rev2guacamole:
    guacamole2guacd:
    guacamole2db:

volumes:
    db_data:
    guacd_drive:
    guacd_record:

services:
    guacamole-rev:
        hostname: guacamole-rev
        image: nginx:mainline-alpine
        restart: on-failure
        volumes:
            - type: bind
              source: ./nginx/
              target: /etc/nginx/conf.d
              read_only: true
        networks:
            rev2guacamole:
        ports:
            - 80:80

    guacamole-db:
        hostname: guacamole-db
        image: mariadb
        restart: on-failure
        volumes:
            - type: bind
              source: ./db_init/
              target: /docker-entrypoint-initdb.d/
              read_only: true
            - type: volume
              source: db_data
              target: '/var/lib/mysql'
        networks:
            guacamole2db:
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: 'Europe/Berlin'

    guacd:
        hostname: guacamole-guacd
        image: guacamole/guacd:0.9.14
        restart: on-failure
        volumes:
            - type: volume
              source: guacd_drive
              target: /drive
            - type: volume
              source: guacd_record
              target: /record
        networks:
            guacamole2guacd:

    guacamole:
        hostname: guacamole
        image: guacamole/guacamole:0.9.14
        restart: on-failure
        networks:
            rev2guacamole:
            guacamole2db:
            guacamole2guacd:
        environment:
            GUACD_HOSTNAME: guacd
            MYSQL_HOSTNAME: guacamole-db
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
